CREATE TABLE "FFPA_RATES" (
  "RATES_YR" NUMBER NOT NULL,
  "RATES_FFPA_FLAT_FEE_AMT" NUMBER(6,2),
  "RATES_FFPA_PER_ACRE_FEE_AMT" NUMBER(6,2),
  "RATES_EASTSIDE_LOC_FLAT_FEE_AMT" NUMBER(6,2),
  "RATES_WESTSIDE_LOC_FLAT_FEE_AMT" NUMBER(6,2),
  "RATES_EASTSIDE_LOC_PER_ACRE_FLAT_FEE_AMT" NUMBER(6,2),
  "RATES_WESTSIDE_LOC_PER_ACRE_FLAT_FEE_AMT" NUMBER(6,2),
  CONSTRAINT "FFPA_RATES_PK" PRIMARY KEY("RATES_YR")
  USING INDEX TABLESPACE FFPA_I
) TABLESPACE FFPA;
/

CREATE PUBLIC SYNONYM "FFPA_RATES" FOR FFPA.FFPA_RATES;
GRANT SELECT ON FFPA.FFPA_RATES TO FFPA_USER;
GRANT INSERT ON FFPA.FFPA_RATES TO FFPA_USER;
GRANT UPDATE ON FFPA.FFPA_RATES TO FFPA_USER;
/
COMMIT;
